version: "3.9"
services:
  app:
    build: ./hostnameapp
    expose:
      - "5000"
  proxy:
    # Image: nginx:alpine
    build: ./nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    links:
      - app
    ports:
      - "8082:80"